apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - hpa.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: restful-web-services
  app.kubernetes.io/managed-by: argocd

# Namespace for all resources
namespace: default

# Images to customize
images:
  - name: restful-web-services
    newName: restful-web-services
    # newName: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/restful-web-services
    newTag: latest
